spring.datasource.url=jdbc:postgresql://localhost:5432/db_incendios_forestales
spring.datasource.username=admin_vallesol
spring.datasource.password=SecurePass2026!
spring.jpa.hibernate.ddl-auto=update
